"""document chunk and processing improvements

Revision ID: ccc346f01b1a
Revises: c3d4e5f6a7b8
Create Date: 2026-08-05 12:53:35.836107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc346f01b1a'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='processing_log_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_logs_document_id'), 'document_processing_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_processing_logs_organization_id'), 'document_processing_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_processing_logs_stage'), 'document_processing_logs', ['stage'], unique=False)
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('section_title', sa.String(length=512), nullable=True))
    op.add_column(
        'document_chunks',
        sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column('document_chunks', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column(
        'documents',
        sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    )
    op.alter_column('document_chunks', 'token_count', server_default=None)
    op.alter_column('documents', 'retry_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'retry_count')
    op.drop_column('document_chunks', 'embedding_model')
    op.drop_column('document_chunks', 'token_count')
    op.drop_column('document_chunks', 'section_title')
    op.drop_column('document_chunks', 'page_number')
    op.drop_index(op.f('ix_document_processing_logs_stage'), table_name='document_processing_logs')
    op.drop_index(op.f('ix_document_processing_logs_organization_id'), table_name='document_processing_logs')
    op.drop_index(op.f('ix_document_processing_logs_document_id'), table_name='document_processing_logs')
    op.drop_table('document_processing_logs')
    # ### end Alembic commands ###
